name: deployer
on:
  push:
    branches:
      - "main"
permissions: {}

jobs:
  builder:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: textlisp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run nix build .#default
        run: nix build .#default
      - name: Upload executable for x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: textlisp-${{ matrix.os }}
          path: result
